name: Test - P4D 4 GPUs

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test-cdk-changes.yaml"

jobs:
  test-gpu-standard:
    runs-on: gpu-standard-runners
    steps:
      - name: Check GPUs
        run: nvidia-smi

      - name: Check Docker
        run: |
          docker info
          docker pull nvidia/cuda:12.0.0-runtime-ubuntu22.04
          docker run --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:12.0.0-runtime-ubuntu22.04 nvidia-smi

  test-p4d:
    runs-on: p4d-gpu-runners
    container:
      image: nvidia/cuda:12.0.0-runtime-ubuntu22.04
    steps:
      - name: Check GPUs
        run: nvidia-smi
